INITIAL_SOLVE_PROMPT_1 = "You are tasked with solving a maze. The maze is a 2D grid with walls, empty spaces, a current player position, and a goal position. The maze has the following encoding:\n* Walls are represented by a '1'\n* Empty spaces are represented by a '0'\n* The current player position is represented by 'P'\n* The goal position is represented by 'G'\nYour objective is to find a step-by-step solution to navigate from the current player position (P) to the goal position (G), moving only through empty spaces while avoiding walls. For reference, the coordinates of the top left corner of the maze are (0,0). You can move to any empty space that is adjacent to the current position in the up, down, left, or right direction. After each move, the maze will be updated to reflect your new position and presented to you again.\nHere is the maze you should solve:\n\n"

INITIAL_SOLVE_PROMPT_COORD_1 = "You are tasked with solving a maze. The maze is a 2D grid with walls, empty spaces, a current player position and a goal position. The maze is encoded using a list of coordinates denoting the walls, a list of coordinates denoting the empty spaces (path), and coordinates for the current player position and goal position.\nYour objective is to find a step-by-step solution to navigate from the current player position (P) to the goal position (G), moving only through empty spaces while avoiding walls. For reference, the coordinates of the top left corner of the maze are (0,0). You can move to any empty space that is adjacent to the current position in the up, down, left, or right direction. After each move, the maze will be updated to reflect your new position and presented to you again.\nHere is the maze you should solve:\n\n"

INITIAL_SOLVE_PROMPT_DIAG_1 = "You are tasked with solving a maze. The maze is a 2D grid with walls, empty spaces, a current player position, and a goal position. The maze has the following encoding:\n* Walls are represented by a '1'\n* Empty spaces are represented by a '0'\n* The current player position is represented by 'P'\n* The goal position is represented by 'G'\nYour objective is to find a step-by-step solution to navigate from the current player position (P) to the goal position (G), moving only through empty spaces while avoiding walls. For reference, the coordinates of the top left corner of the maze are (0,0). You can move to any empty space that is adjacent to the current position: either up, down, left, right, or any diagonal. After each move, the maze will be updated to reflect your new position and presented to you again.\nHere is the maze you should solve:\n\n"

INITIAL_SOLVE_PROMPT_VISION = "# Maze Navigation Task\n\nYou are tasked with solving a maze provided to you as an image. You goal is to complete the maze, move-by-move, by finding a path from a start position to an end position. Below are detailed instructions for the task.\n\n## Maze Representation\n\nThe attached image is a maze represented as a 2D grid. Each cell in the maze has coordinates displayed as (row,column), with (0,0) being the top-left corner. The grid uses the following color coding:\n\n* WHITE cells (walls): These are obstacles you CANNOT move through\n* DARK GREY cells (paths): These are empty cells you CAN move through\n* BLUE cell (player): Your current position in the maze\n* RED cell (goal): Your destination that you need to reach\n\n## Movement Rules\n\n1. You can ONLY move to adjacent cells in four directions: UP, DOWN, LEFT, or RIGHT\n2. Diagonal movement is NOT allowed\n3. You can ONLY move through empty (DARK GREY) cells\n4. You CANNOT move through walls (WHITE cells)\n5. Each move must be to a directly adjacent cell (no skipping cells)\n\n## Your Task\n\nNavigate from your current position (BLUE cell) to the goal (RED cell) by providing a sequence of coordinates, one move at a time.\n\n## How to Respond\n\n1. Analyze the maze carefully \n2. Identify a valid path from your current position to the goal\n3. Provide your next move as coordinates in the format (row,column)\n4. After each of your moves, I will show you an updated maze with your new position\n5. Continue providing one move at a time until you reach the goal\n\n## Success Condition\n\nThe task is completed when you successfully reach the RED goal cell.\n\n## Example Response\n\nTo move to the cell below your current position, you would respond with the coordinates of that cell, such as:\n\n'Next move: (5,3)'\n\nHere is the maze you need to solve:\n"

INITIAL_SOLVE_PROMPT_VISION_DIAG = "# Maze Navigation Task\n\nYou are tasked with solving a maze provided to you as an image. You goal is to complete the maze, move-by-move, by finding a path from a start position to an end position. Below are detailed instructions for the task.\n\n## Maze Representation\n\nThe attached image is a maze represented as a 2D grid. Each cell in the maze has coordinates displayed as (row,column), with (0,0) being the top-left corner. The grid uses the following color coding:\n\n* WHITE cells (walls): These are obstacles you CANNOT move through\n* DARK GREY cells (paths): These are empty cells you CAN move through\n* BLUE cell (player): Your current position in the maze\n* RED cell (goal): Your destination that you need to reach\n\n## Movement Rules\n\n1. You can ONLY move to adjacent cells in five directions: UP, DOWN, LEFT, RIGHT, or DIAGONAL\n2. You can ONLY move through empty (DARK GREY) cells\n3. You CANNOT move through walls (WHITE cells)\n4. Each move must be to a directly adjacent cell (no skipping cells)\n\n## Your Task\n\nNavigate from your current position (BLUE cell) to the goal (RED cell) by providing a sequence of coordinates, one move at a time.\n\n## How to Respond\n\n1. Analyze the maze carefully \n2. Identify a valid path from your current position to the goal\n3. Provide your next move as coordinates in the format (row,column)\n4. After each of your moves, I will show you an updated maze with your new position\n5. Continue providing one move at a time until you reach the goal\n\n## Success Condition\n\nThe task is completed when you successfully reach the RED goal cell.\n\n## Example Response\n\nTo move to the cell below your current position, you would respond with the coordinates of that cell, such as:\n\n'Next move: (5,3)'\n\nHere is the maze you need to solve:\n"

INITIAL_SOLVE_PROMPT_DIAG_COORD_1 = "You are tasked with solving a maze. The maze is a 2D grid with walls, empty spaces, a current player position and a goal position. The maze is encoded using a list of coordinates denoting the walls, a list of coordinates denoting the empty spaces (path), and coordinates for the current player position and goal position.\nYour objective is to find a step-by-step solution to navigate from the current player position (P) to the goal position (G), moving only through empty spaces while avoiding walls. For reference, the coordinates of the top left corner of the maze are (0,0). You can move to any empty space that is adjacent to the current position: either up, down, left, right, or any diagonal. After each move, the maze will be updated to reflect your new position and presented to you again.\nHere is the maze you should solve:\n\n"

INITIAL_SOLVE_PROMPT_2 = "\n\nPlease provide the coordinates of your next move."

UPDATE_SOLVE_PROMPT_1 = "\n\nHere is the current state of the maze after your latest move:\n\n"

UPDATE_SOLVE_PROMPT_2 = "\n\nPlease provide the coordinates of your next move."

RECOGNIZE_AND_GENERATE_PROMPT = '\n\nFor the maze you were tasked to solve, please provide: (1) the name of the general shape formed by the empty spaces (corridors), and (2) a new maze of the same size, with empty spaces that form the same shape. Encode your new maze using the same format as the original.\n\nFor example, if you answered (1) by naming the general shape of the path as "{shape}" (where "{shape}" is the name of the shape), then in (2), you should generate a new maze that meets the following criteria:\n* It has the same size as the original maze\n* It includes a valid path from P to G that can be reached through empty spaces\n* It is not an identical copy of the original maze\n* The general shape formed by its empty spaces (corridors) is recognizable as "{shape}".\n\n'

RECOGNIZE_AND_GENERATE_PROMPT_VISION = "\n\n# Maze Shape Recognition and Generation Task\n\nNow that you have solved the maze, you need to perform to additional tasks:\n\n1. Recognize the shape of the maze you just solved\n2. Generate a new maze with the same shape\n\nLet me explain each of these additional tasks.\n\n## Part 1: Shape Recognition\n\nExamine the maze you just solved and identify the overall pattern or shape formed by the non-wall cells (corridors). Note that this should NOT be the shape of the path from start to finish, but rather the shape formed by ALL non-wall cells, including empty cells, start cell, and finish cell.\n\nProvide the name of the shape you recognize. Be specific and explain your reasoning.\n\n## Part 2: Maze Generation\n\nCreate a new maze with the following specifications:\n\n### Requirements:\n\n1. **Same dimensions**: Your new maze must have exactly the same height and width as the original maze\n2. **Same shape pattern**: The corridors (non-wall cells) must form the same general shape you identified in Part 1\n3. **Valid path**: There must be at least one valid path from start to goal positions\n4. **Different layout**: While maintaining the same shape, your maze should NOT be an identical copy of the original\n5. **Proper encoding**: Use the same encoding format as described below\n\n### Encoding Format:\n\nEncode your maze as a text matrix with the following symbols:\n* '1' for walls (representing WHITE cells)\n* '0' for empty corridors (representing DARK GREY cells)\n* 'S' for the player starting position (representing the BLUE cell)\n* 'G' for the goal position (representing the RED cell)\n\n### Example Response:\n\nIf you identified the shape as a '{shape}', your response would be:\n\nPart 1: The maze corridors form a {shape} shape. This is evident from {explanation}.\n\nPart 2: Here is my new {shape}-shaped maze with the same dimensions (5x5):\n\n```\n1 1 1 1 1\n1 S 0 0 1\n1 1 1 0 1\n1 G 0 0 1\n1 1 1 1 1\n```\n\nPlease provide both Part 1 (recognition) and Part 2 (generation) in your response.\n"